In [ ]:
# Output format should look like below 
# {
#   'mean': [axis1, axis2, flattened],
#   'variance': [axis1, axis2, flattened],
#   'standard deviation': [axis1, axis2, flattened],
#   'max': [axis1, axis2, flattened],
#   'min': [axis1, axis2, flattened],
#   'sum': [axis1, axis2, flattened]
# }

# If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: 
# "List must contain nine numbers." 
# The values in the returned dictionary should be lists and not Numpy arrays.

# For example, calculate([0,1,2,3,4,5,6,7,8]) should return:

# {
#   'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 
#   'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 
#   'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
#   'max': [[6, 7, 8], [2, 5, 8], 8],
#   'min': [[0, 1, 2], [0, 3, 6], 0],
#   'sum': [[9, 12, 15], [3, 12, 21], 36]
# }

In [36]:
# once 3 row icin islemler, sonra 3 column icin sonra tamamini kapsicak sekilde duz listeymis gibi
import numpy as np

def calculate(arglist):
# uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements 
# in a 3 x 3 matrix.
    if len(arglist)>9:
        raise ValueError("List must contain nine numbers.")
   

# The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary 
# containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.
    calculations=dict()
    numpy_array = np.array(arglist).reshape(3,3)
    cols = np.array([numpy_array[0],numpy_array[1],numpy_array[2]])
    print(cols)
    rows = np.array([[numpy_array[0][0],numpy_array[1][0],numpy_array[2][0]],[numpy_array[0][1],numpy_array[1][1],numpy_array[2][1]],[numpy_array[0][2],numpy_array[1][2],numpy_array[2][2]]])
    print(rows)
    calculations['mean']=[[rows[0].mean(),rows[1].mean(),rows[2].mean()],[cols[0].mean(),cols[1].mean(),cols[2].mean()],numpy_array.mean()]
    calculations['standard deviation']=[[rows[0].std(),rows[1].std(),rows[2].std()],[cols[0].std(),cols[1].std(),cols[2].std()],numpy_array.std()]
    # doing with list comprehension 
    calculations['variance']=[[np.var(row) for row in rows],[np.var(col) for col in cols],np.var(arglist)]
    calculations['min']=[[min(row) for row in rows],[min(col) for col in cols],min(arglist)]
    calculations['max']=[[max(row) for row in rows],[max(col) for col in cols],max(arglist)]
    calculations['sum']=[[sum(row) for row in rows],[max(col) for col in cols],sum(arglist)]
    
    return calculations

In [37]:
import numpy as np
listArg = [0,1,2,3,4,5,6,7,8]
numpy_array = np.array(listArg).reshape(3,3)
print(numpy_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
thereturn = calculate([0,1,2,3,4,5,6,7,8])
print(thereturn)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'min': [[0, 1, 2], [0, 3, 6], 0], 'max': [[6, 7, 8], [2, 5, 8], 8], 'sum': [[9, 12, 15], [2, 5, 8], 36]}
